### ISSUE TITLE
Where is the API document on Barco site?

### ISSUE THREAD

**Issue by avantcontra** [kyelewisstgc/EventMaster-Python#1]
Hi Kye,

Great py lib!

I only found a JSONRPC API document on barco site:
[JSONRPC API](http://barco.com.cn/api/sitecore/TdeFiles/Download?FileNumber=TDE7730&TdeType=1&Revision=00)

Where is the API document you used on Barco site?

Thanks.
Contra

**Comment by kyelewisstgc** [comment]
Hey Contra,

No document that I'm aware of for the XML protocol. Some reverse engineering between the client- it's a fairly straightforward protocol.

**Comment by avantcontra** [comment]
Got it. Thanks!
